server:
  port: 8084

spring:
  data:
    mongodb:
      authentication-database: tp_final_catalogo
      username: admin
      password: admin
      database: tp_final_catalogo
      port: 27017
      host: mongodb #localhost 

resilience4j:
  circuitbreaker:
    instances:      
      catalogs:
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 3
        failureRateThreshold: 50
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 15000
        permittedNumberOfCallsInHalfOpenState: 3
        registerHealthIndicator: true
        allowHealthIndicatorToFail: false
        
  retry:
    instances:
      catalogs:
        maxAttempts: 3
        waitDuration: 1000
        retryExceptions[0]: feign.FeignException$InternalServerError

management:
  health:
    circuitbreakers:
      enabled: true

info:
  app:
    name: ${spring.application.name}
    version: 1.0.0
    description: Catalog Microservice
