server:
  port: 8082

spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://mysql:3306/tp_final #jdbc:mysql://localhost:3306/tp_final
    username: root
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver

info:
  app:
    name: ${spring.application.name}
    version: 1.0.0
    description: Movie Microservice
