server:
  port: 8086
  
spring:
  data:
    mongodb:
      authentication-database: tp_final_series
      username: admin
      password: admin
      database: tp_final_series
      port: 27017
      host: mongodb #localhost

info:
  app:
    name: ${spring.application.name}
    version: 1.0.0
    description: Series Microservice
