server:
  port: 8888
spring:
  application:
    name: config-service
  zipkin:
    enabled: true
    baseUrl: http://zipkin:9411
  cloud:
    config:
      server:
        git:
          uri: https://github.com/juanmalescano/Final-Especializacion-BackEnd
eureka:
  client:
    service-url:
      defaultZone: http://EUREKA-SERVER:8761/eureka/ #http://localhost:8761/eureka
